// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: file_upload.proto

package fileuploadv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_file_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_file_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_file_upload_proto_rawDescGZIP(), []int{0}
}

func (x *FileChunk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatus) Reset() {
	*x = UploadStatus{}
	mi := &file_file_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatus) ProtoMessage() {}

func (x *UploadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_file_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatus.ProtoReflect.Descriptor instead.
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return file_file_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadStatus) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadStatus) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

var File_file_upload_proto protoreflect.FileDescriptor

const file_file_upload_proto_rawDesc = "" +
	"\n" +
	"\x11file_upload.proto\x12\n" +
	"fileupload\"3\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"T\n" +
	"\fUploadStatus\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha2562P\n" +
	"\vFileService\x12A\n" +
	"\n" +
	"FileUpload\x12\x15.fileupload.FileChunk\x1a\x18.fileupload.UploadStatus\"\x00(\x01B\x1dZ\x1bfileupload.v1; fileuploadv1b\x06proto3"

var (
	file_file_upload_proto_rawDescOnce sync.Once
	file_file_upload_proto_rawDescData []byte
)

func file_file_upload_proto_rawDescGZIP() []byte {
	file_file_upload_proto_rawDescOnce.Do(func() {
		file_file_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_upload_proto_rawDesc), len(file_file_upload_proto_rawDesc)))
	})
	return file_file_upload_proto_rawDescData
}

var file_file_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_file_upload_proto_goTypes = []any{
	(*FileChunk)(nil),    // 0: fileupload.FileChunk
	(*UploadStatus)(nil), // 1: fileupload.UploadStatus
}
var file_file_upload_proto_depIdxs = []int32{
	0, // 0: fileupload.FileService.FileUpload:input_type -> fileupload.FileChunk
	1, // 1: fileupload.FileService.FileUpload:output_type -> fileupload.UploadStatus
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_upload_proto_init() }
func file_file_upload_proto_init() {
	if File_file_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_upload_proto_rawDesc), len(file_file_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_upload_proto_goTypes,
		DependencyIndexes: file_file_upload_proto_depIdxs,
		MessageInfos:      file_file_upload_proto_msgTypes,
	}.Build()
	File_file_upload_proto = out.File
	file_file_upload_proto_goTypes = nil
	file_file_upload_proto_depIdxs = nil
}
