// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: file_upload.proto

package fileuploadv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ChunkId       int64                  `protobuf:"varint,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunkRequest) Reset() {
	*x = UploadChunkRequest{}
	mi := &file_file_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunkRequest) ProtoMessage() {}

func (x *UploadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunkRequest.ProtoReflect.Descriptor instead.
func (*UploadChunkRequest) Descriptor() ([]byte, []int) {
	return file_file_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadChunkRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadChunkRequest) GetChunkId() int64 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *UploadChunkRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *UploadChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceivedBytes int64                  `protobuf:"varint,1,opt,name=received_bytes,json=receivedBytes,proto3" json:"received_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunkResponse) Reset() {
	*x = UploadChunkResponse{}
	mi := &file_file_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunkResponse) ProtoMessage() {}

func (x *UploadChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunkResponse.ProtoReflect.Descriptor instead.
func (*UploadChunkResponse) Descriptor() ([]byte, []int) {
	return file_file_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadChunkResponse) GetReceivedBytes() int64 {
	if x != nil {
		return x.ReceivedBytes
	}
	return 0
}

type CompleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	TotalChunks   int64                  `protobuf:"varint,2,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteFileRequest) Reset() {
	*x = CompleteFileRequest{}
	mi := &file_file_upload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFileRequest) ProtoMessage() {}

func (x *CompleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_upload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFileRequest.ProtoReflect.Descriptor instead.
func (*CompleteFileRequest) Descriptor() ([]byte, []int) {
	return file_file_upload_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CompleteFileRequest) GetTotalChunks() int64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

type CompleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteFileResponse) Reset() {
	*x = CompleteFileResponse{}
	mi := &file_file_upload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFileResponse) ProtoMessage() {}

func (x *CompleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_upload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFileResponse.ProtoReflect.Descriptor instead.
func (*CompleteFileResponse) Descriptor() ([]byte, []int) {
	return file_file_upload_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_file_upload_proto protoreflect.FileDescriptor

const file_file_upload_proto_rawDesc = "" +
	"\n" +
	"\x11file_upload.proto\x12\n" +
	"fileupload\"w\n" +
	"\x12UploadChunkRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\x03R\achunkId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"<\n" +
	"\x13UploadChunkResponse\x12%\n" +
	"\x0ereceived_bytes\x18\x01 \x01(\x03R\rreceivedBytes\"T\n" +
	"\x13CompleteFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\ftotal_chunks\x18\x02 \x01(\x03R\vtotalChunks\"0\n" +
	"\x14CompleteFileResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb6\x01\n" +
	"\vFileService\x12R\n" +
	"\vUploadChunk\x12\x1e.fileupload.UploadChunkRequest\x1a\x1f.fileupload.UploadChunkResponse\"\x00(\x01\x12S\n" +
	"\fCompleteFile\x12\x1f.fileupload.CompleteFileRequest\x1a .fileupload.CompleteFileResponse\"\x00B\x1dZ\x1bfileupload.v1; fileuploadv1b\x06proto3"

var (
	file_file_upload_proto_rawDescOnce sync.Once
	file_file_upload_proto_rawDescData []byte
)

func file_file_upload_proto_rawDescGZIP() []byte {
	file_file_upload_proto_rawDescOnce.Do(func() {
		file_file_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_upload_proto_rawDesc), len(file_file_upload_proto_rawDesc)))
	})
	return file_file_upload_proto_rawDescData
}

var file_file_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_file_upload_proto_goTypes = []any{
	(*UploadChunkRequest)(nil),   // 0: fileupload.UploadChunkRequest
	(*UploadChunkResponse)(nil),  // 1: fileupload.UploadChunkResponse
	(*CompleteFileRequest)(nil),  // 2: fileupload.CompleteFileRequest
	(*CompleteFileResponse)(nil), // 3: fileupload.CompleteFileResponse
}
var file_file_upload_proto_depIdxs = []int32{
	0, // 0: fileupload.FileService.UploadChunk:input_type -> fileupload.UploadChunkRequest
	2, // 1: fileupload.FileService.CompleteFile:input_type -> fileupload.CompleteFileRequest
	1, // 2: fileupload.FileService.UploadChunk:output_type -> fileupload.UploadChunkResponse
	3, // 3: fileupload.FileService.CompleteFile:output_type -> fileupload.CompleteFileResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_upload_proto_init() }
func file_file_upload_proto_init() {
	if File_file_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_upload_proto_rawDesc), len(file_file_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_upload_proto_goTypes,
		DependencyIndexes: file_file_upload_proto_depIdxs,
		MessageInfos:      file_file_upload_proto_msgTypes,
	}.Build()
	File_file_upload_proto = out.File
	file_file_upload_proto_goTypes = nil
	file_file_upload_proto_depIdxs = nil
}
