// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: file_upload.proto

package fileuploadv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`               // original filename
	ChunkId       int64                  `protobuf:"varint,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"` // 0..N-1
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                  // byte offset
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                       // chunk data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunkRequest) Reset() {
	*x = UploadChunkRequest{}
	mi := &file_file_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunkRequest) ProtoMessage() {}

func (x *UploadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunkRequest.ProtoReflect.Descriptor instead.
func (*UploadChunkRequest) Descriptor() ([]byte, []int) {
	return file_file_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadChunkRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadChunkRequest) GetChunkId() int64 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *UploadChunkRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *UploadChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      int64                  `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunkResponse) Reset() {
	*x = UploadChunkResponse{}
	mi := &file_file_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunkResponse) ProtoMessage() {}

func (x *UploadChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunkResponse.ProtoReflect.Descriptor instead.
func (*UploadChunkResponse) Descriptor() ([]byte, []int) {
	return file_file_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadChunkResponse) GetReceived() int64 {
	if x != nil {
		return x.Received
	}
	return 0
}

type CompleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	TotalSize     int64                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteFileRequest) Reset() {
	*x = CompleteFileRequest{}
	mi := &file_file_upload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFileRequest) ProtoMessage() {}

func (x *CompleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_upload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFileRequest.ProtoReflect.Descriptor instead.
func (*CompleteFileRequest) Descriptor() ([]byte, []int) {
	return file_file_upload_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CompleteFileRequest) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *CompleteFileRequest) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

type CompleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteFileResponse) Reset() {
	*x = CompleteFileResponse{}
	mi := &file_file_upload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFileResponse) ProtoMessage() {}

func (x *CompleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_upload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFileResponse.ProtoReflect.Descriptor instead.
func (*CompleteFileResponse) Descriptor() ([]byte, []int) {
	return file_file_upload_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CompleteFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CompleteFileResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_file_upload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_upload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_file_upload_proto_rawDescGZIP(), []int{4}
}

func (x *CheckRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadedSize  int64                  `protobuf:"varint,1,opt,name=uploadedSize,proto3" json:"uploadedSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_file_upload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_upload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_file_upload_proto_rawDescGZIP(), []int{5}
}

func (x *CheckResponse) GetUploadedSize() int64 {
	if x != nil {
		return x.UploadedSize
	}
	return 0
}

var File_file_upload_proto protoreflect.FileDescriptor

const file_file_upload_proto_rawDesc = "" +
	"\n" +
	"\x11file_upload.proto\x12\n" +
	"fileupload\"w\n" +
	"\x12UploadChunkRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\x03R\achunkId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"1\n" +
	"\x13UploadChunkResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\x03R\breceived\"s\n" +
	"\x13CompleteFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\"\\\n" +
	"\x14CompleteFileResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\"*\n" +
	"\fCheckRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"3\n" +
	"\rCheckResponse\x12\"\n" +
	"\fuploadedSize\x18\x01 \x01(\x03R\fuploadedSize2\xf2\x01\n" +
	"\vFileService\x12N\n" +
	"\vUploadChunk\x12\x1e.fileupload.UploadChunkRequest\x1a\x1f.fileupload.UploadChunkResponse\x12Q\n" +
	"\fCompleteFile\x12\x1f.fileupload.CompleteFileRequest\x1a .fileupload.CompleteFileResponse\x12@\n" +
	"\tCheckFile\x12\x18.fileupload.CheckRequest\x1a\x19.fileupload.CheckResponseB\x1cZ\x1afileupload.v1;fileuploadv1b\x06proto3"

var (
	file_file_upload_proto_rawDescOnce sync.Once
	file_file_upload_proto_rawDescData []byte
)

func file_file_upload_proto_rawDescGZIP() []byte {
	file_file_upload_proto_rawDescOnce.Do(func() {
		file_file_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_upload_proto_rawDesc), len(file_file_upload_proto_rawDesc)))
	})
	return file_file_upload_proto_rawDescData
}

var file_file_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_file_upload_proto_goTypes = []any{
	(*UploadChunkRequest)(nil),   // 0: fileupload.UploadChunkRequest
	(*UploadChunkResponse)(nil),  // 1: fileupload.UploadChunkResponse
	(*CompleteFileRequest)(nil),  // 2: fileupload.CompleteFileRequest
	(*CompleteFileResponse)(nil), // 3: fileupload.CompleteFileResponse
	(*CheckRequest)(nil),         // 4: fileupload.CheckRequest
	(*CheckResponse)(nil),        // 5: fileupload.CheckResponse
}
var file_file_upload_proto_depIdxs = []int32{
	0, // 0: fileupload.FileService.UploadChunk:input_type -> fileupload.UploadChunkRequest
	2, // 1: fileupload.FileService.CompleteFile:input_type -> fileupload.CompleteFileRequest
	4, // 2: fileupload.FileService.CheckFile:input_type -> fileupload.CheckRequest
	1, // 3: fileupload.FileService.UploadChunk:output_type -> fileupload.UploadChunkResponse
	3, // 4: fileupload.FileService.CompleteFile:output_type -> fileupload.CompleteFileResponse
	5, // 5: fileupload.FileService.CheckFile:output_type -> fileupload.CheckResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_upload_proto_init() }
func file_file_upload_proto_init() {
	if File_file_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_upload_proto_rawDesc), len(file_file_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_upload_proto_goTypes,
		DependencyIndexes: file_file_upload_proto_depIdxs,
		MessageInfos:      file_file_upload_proto_msgTypes,
	}.Build()
	File_file_upload_proto = out.File
	file_file_upload_proto_goTypes = nil
	file_file_upload_proto_depIdxs = nil
}
